/* generated by scripts/build-pwa.mjs */
const CACHE = 'forge-5f2868dcd793';
const FONT_CACHE = 'forge-fonts';
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];
const BASE = new URL(self.registration.scope).pathname;
const PRECACHE = ["_expo/static/js/web/AppEntry-4c823269e4f20c509c9cf5c01739cb99.js","apple-touch-icon.png","fonts/inter.woff2","fonts/jetbrains-mono.woff2","icon-192.png","icon-512.png","index.html","manifest.json","metadata.json","vbt/assets/index-4q3ZZpdT.js","vbt/assets/index-DpBaX75b.css","vbt/icons/apple-touch-icon.png","vbt/icons/icon-192.png","vbt/icons/icon-512.png","vbt/index.html"].map((p) => BASE + p);

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONT_CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Navigations must never be answered with a response marked `redirected`
   (some hosts redirect /index.html to ./) — rewrap the body if needed. */
async function serveShell(path, request) {
  const cached = await caches.match(path);
  if (!cached) return fetch(request);
  if (!cached.redirected) return cached;
  const body = await cached.blob();
  return new Response(body, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
}

/* Network-first for the HTML shell: a refresh while online always gets the
   CURRENT index.html (matching the freshly-deployed bundle hash), so a stale
   cached shell can never point at a bundle that has been evicted/replaced
   (the black-screen bug). Offline / slow network falls back to the cached
   shell. Hashed assets stay cache-first below (immutable, safe). */
async function networkFirstShell(shellPath, request) {
  try {
    const ctrl = new AbortController();
    const timer = setTimeout(function () { ctrl.abort(); }, 3500);
    const net = await fetch(request, { signal: ctrl.signal });
    clearTimeout(timer);
    if (net && net.ok) {
      if (net.redirected) {
        const body = await net.blob();
        return new Response(body, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
      }
      caches.open(CACHE).then(function (c) { c.put(shellPath, net.clone()); }).catch(function () {});
      return net;
    }
    throw new Error('status ' + (net && net.status));
  } catch (err) {
    return serveShell(shellPath, request);
  }
}

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) {
    // vbt sub-app uses Google Fonts — cache them so its UI works offline
    if (FONT_HOSTS.includes(url.hostname)) {
      e.respondWith(
        caches.match(e.request).then(
          (r) =>
            r ||
            fetch(e.request).then((res) => {
              if (res.ok) {
                const copy = res.clone();
                caches.open(FONT_CACHE).then((c) => c.put(e.request, copy));
              }
              return res;
            })
        )
      );
    }
    return;
  }
  if (e.request.mode === 'navigate') {
    // the Velocity tab iframe navigates to the vbt sub-app — don't hand it the forge shell
    const shell = url.pathname.startsWith(BASE + 'vbt/') ? BASE + 'vbt/index.html' : BASE + 'index.html';
    e.respondWith(networkFirstShell(shell, e.request));
    return;
  }
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(
      (r) =>
        r ||
        fetch(e.request).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(e.request, copy));
          }
          return res;
        })
    )
  );
});
