/* generated by scripts/build-pwa.mjs */
const CACHE = 'forge-82f72e2c00c0';
const BASE = new URL(self.registration.scope).pathname;
const PRECACHE = ["_expo/static/js/web/AppEntry-3e1904165ca72743dd43c10d22010c3d.js","apple-touch-icon.png","icon-192.png","icon-512.png","index.html","manifest.json","metadata.json"].map((p) => BASE + p);

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Navigations must never be answered with a response marked `redirected`
   (some hosts redirect /index.html to ./) — rewrap the body if needed. */
async function serveIndex(request) {
  const cached = await caches.match(BASE + 'index.html');
  if (!cached) return fetch(request);
  if (!cached.redirected) return cached;
  const body = await cached.blob();
  return new Response(body, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
}

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;
  if (e.request.mode === 'navigate') {
    e.respondWith(serveIndex(e.request));
    return;
  }
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(
      (r) =>
        r ||
        fetch(e.request).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(e.request, copy));
          }
          return res;
        })
    )
  );
});
