/* generated by scripts/build-pwa.mjs */
const CACHE = 'forge-16225cab31bd';
const FONT_CACHE = 'forge-fonts';
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];
const BASE = new URL(self.registration.scope).pathname;
const PRECACHE = ["_expo/static/js/web/AppEntry-ed41345838578fbee2c989b18a7571e5.js","apple-touch-icon.png","icon-192.png","icon-512.png","index.html","manifest.json","metadata.json","vbt/assets/index-t8k70m7N.js","vbt/assets/index-yOPixjYG.css","vbt/icons/apple-touch-icon.png","vbt/icons/icon-192.png","vbt/icons/icon-512.png","vbt/index.html"].map((p) => BASE + p);

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONT_CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Navigations must never be answered with a response marked `redirected`
   (some hosts redirect /index.html to ./) — rewrap the body if needed. */
async function serveShell(path, request) {
  const cached = await caches.match(path);
  if (!cached) return fetch(request);
  if (!cached.redirected) return cached;
  const body = await cached.blob();
  return new Response(body, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
}

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) {
    // vbt sub-app uses Google Fonts — cache them so its UI works offline
    if (FONT_HOSTS.includes(url.hostname)) {
      e.respondWith(
        caches.match(e.request).then(
          (r) =>
            r ||
            fetch(e.request).then((res) => {
              if (res.ok) {
                const copy = res.clone();
                caches.open(FONT_CACHE).then((c) => c.put(e.request, copy));
              }
              return res;
            })
        )
      );
    }
    return;
  }
  if (e.request.mode === 'navigate') {
    // the Velocity tab iframe navigates to the vbt sub-app — don't hand it the forge shell
    const shell = url.pathname.startsWith(BASE + 'vbt/') ? BASE + 'vbt/index.html' : BASE + 'index.html';
    e.respondWith(serveShell(shell, e.request));
    return;
  }
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(
      (r) =>
        r ||
        fetch(e.request).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(e.request, copy));
          }
          return res;
        })
    )
  );
});
