/* Builds the offline-capable web app:
   1. expo export -p web  → dist/
   2. writes dist/sw.js with a precache manifest of every exported file,
      versioned by content hash so updates replace old caches cleanly. */
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = join(root, 'dist');
const vbtDir = join(root, '..', 'vbt');

console.log('▸ expo export -p web');
execSync('npx expo export -p web', { cwd: root, stdio: 'inherit' });

// FORGE Velocity sub-app: embedded build (no own service worker) into dist/vbt/
console.log('▸ vbt embedded build → dist/vbt');
execSync(`npm run build -- --outDir "${join(dist, 'vbt')}" --emptyOutDir`, {
  cwd: vbtDir,
  stdio: 'inherit',
  env: { ...process.env, VBT_EMBED: '1' },
});

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
})(dist);

const hash = createHash('md5');
const urls = [];
for (const f of files.sort()) {
  const rel = relative(dist, f).split('\\').join('/');
  if (rel === 'sw.js') continue;
  if (rel.includes('eruda')) continue; // vbt's lazy debug console (?debug) — not worth 500 kB of precache
  hash.update(rel);
  hash.update(readFileSync(f));
  urls.push(rel);
}
const version = hash.digest('hex').slice(0, 12);

const sw = `/* generated by scripts/build-pwa.mjs */
const CACHE = 'forge-${version}';
const FONT_CACHE = 'forge-fonts';
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];
const BASE = new URL(self.registration.scope).pathname;
const PRECACHE = ${JSON.stringify(urls)}.map((p) => BASE + p);

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONT_CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Navigations must never be answered with a response marked \`redirected\`
   (some hosts redirect /index.html to ./) — rewrap the body if needed. */
async function serveShell(path, request) {
  const cached = await caches.match(path);
  if (!cached) return fetch(request);
  if (!cached.redirected) return cached;
  const body = await cached.blob();
  return new Response(body, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
}

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) {
    // vbt sub-app uses Google Fonts — cache them so its UI works offline
    if (FONT_HOSTS.includes(url.hostname)) {
      e.respondWith(
        caches.match(e.request).then(
          (r) =>
            r ||
            fetch(e.request).then((res) => {
              if (res.ok) {
                const copy = res.clone();
                caches.open(FONT_CACHE).then((c) => c.put(e.request, copy));
              }
              return res;
            })
        )
      );
    }
    return;
  }
  if (e.request.mode === 'navigate') {
    // the Velocity tab iframe navigates to the vbt sub-app — don't hand it the forge shell
    const shell = url.pathname.startsWith(BASE + 'vbt/') ? BASE + 'vbt/index.html' : BASE + 'index.html';
    e.respondWith(serveShell(shell, e.request));
    return;
  }
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(
      (r) =>
        r ||
        fetch(e.request).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(e.request, copy));
          }
          return res;
        })
    )
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`▸ wrote dist/sw.js — ${urls.length} precached files, cache forge-${version}`);
