/* Built-in exercise library. ids are stable — history references them. */
const E = (id, name, group, equipment) => ({ id, name, group, equipment, notes: '', hasVideo: false, builtin: true });

export const SEED_EXERCISES = [
  E('bench-press', 'Bench Press', 'Chest', 'Barbell'),
  E('incline-db-press', 'Incline DB Press', 'Chest', 'Dumbbell'),
  E('db-fly', 'Dumbbell Fly', 'Chest', 'Dumbbell'),
  E('cable-crossover', 'Cable Crossover', 'Chest', 'Cable'),
  E('push-up', 'Push-up', 'Chest', 'Bodyweight'),
  E('deadlift', 'Deadlift', 'Back', 'Barbell'),
  E('barbell-row', 'Barbell Row', 'Back', 'Barbell'),
  E('lat-pulldown', 'Lat Pulldown', 'Back', 'Cable'),
  E('pull-up', 'Pull-up', 'Back', 'Bodyweight'),
  E('seated-cable-row', 'Seated Cable Row', 'Back', 'Cable'),
  E('squat', 'Back Squat', 'Legs', 'Barbell'),
  E('front-squat', 'Front Squat', 'Legs', 'Barbell'),
  E('leg-press', 'Leg Press', 'Legs', 'Machine'),
  E('romanian-deadlift', 'Romanian Deadlift', 'Legs', 'Barbell'),
  E('leg-curl', 'Leg Curl', 'Legs', 'Machine'),
  E('leg-extension', 'Leg Extension', 'Legs', 'Machine'),
  E('calf-raise', 'Calf Raise', 'Legs', 'Machine'),
  E('lunge', 'Walking Lunge', 'Legs', 'Dumbbell'),
  E('overhead-press', 'Overhead Press', 'Shoulders', 'Barbell'),
  E('db-shoulder-press', 'DB Shoulder Press', 'Shoulders', 'Dumbbell'),
  E('lateral-raise', 'Lateral Raise', 'Shoulders', 'Dumbbell'),
  E('rear-delt-fly', 'Rear Delt Fly', 'Shoulders', 'Dumbbell'),
  E('face-pull', 'Face Pull', 'Shoulders', 'Cable'),
  E('bicep-curl', 'Barbell Curl', 'Arms', 'Barbell'),
  E('db-curl', 'Dumbbell Curl', 'Arms', 'Dumbbell'),
  E('hammer-curl', 'Hammer Curl', 'Arms', 'Dumbbell'),
  E('tricep-pushdown', 'Tricep Pushdown', 'Arms', 'Cable'),
  E('skull-crusher', 'Skull Crusher', 'Arms', 'Barbell'),
  E('dip', 'Dip', 'Arms', 'Bodyweight'),
  E('plank', 'Plank', 'Core', 'Bodyweight'),
  E('cable-crunch', 'Cable Crunch', 'Core', 'Cable'),
  E('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 'Bodyweight'),
];
